rewrite function get_altitude_intersection
PnX-SI/RefGeo pull request #10
Opened 2023-04-20 10:06 UTC by jbrieuclp

Corrige [PnX-SI/RefGeo/issues/9](https://github.com/PnX-SI/RefGeo/issues/9) et https://github.com/PnX-SI/GeoNature/issues/2044

2023-04-20 14:22 UTC, jpm-cbna requested changes
A priori, il faudrait reformater le fichier avec Black car le check correspondant de la PR ne passe pas : https://github.com/PnX-SI/RefGeo/pull/10/checks

J'ai juste rajouter un commentaire concernant la simplification et l'amélioration de la lecture du SQL (forme) mais sinon tout me semble ok sur le fond.

2023-04-20 14:22 UTC, jpm-cbna commented on src/ref_geo/migrations/versions/1fdac7036dd9_rewrite_fct_get_altitude_intersection.py
> +                WHERE public.ST_Intersects(a,geom);
Je ne suis pas certain que tous les alias présent dans les requêtes de cette section de code soit vraiment nécessaire. Cela vaudrait le coup de les supprimer s'ils sont inutiles afin de simplifier les requêtes.

Au passage, passer tous les "as" restant en majuscule "AS" serait mieux.

2023-06-22 14:07 UTC, mvergez commented
J'ai testé et ça fonctionne super ! Merci beaucoup !

Serait-il possible de passer `black` pour formatter le fichier de migration ?

2023-09-15 14:03 UTC, amandine-sahl commented on src/ref_geo/migrations/versions/1fdac7036dd9_rewrite_fct_get_altitude_intersection.py
> +              IF is_vectorized IS NULL THEN
Voir la possibilité d'ajouter un sous cas lorsque les géometries sont de type point : 

```sql
  IF is_vectorized IS NULL AND st_geometrytype(myGeom) = 'ST_Point' THEN
        RETURN QUERY
        WITH alt AS (
            SELECT st_value(rast, public.st_transform(myGeom,thesrid))::int altitude
            FROM ref_geo.dem AS altitude
            WHERE public.st_intersects(rast,public.st_transform(myGeom,thesrid))
        )
        SELECT min(altitude) AS altitude_min, max(altitude)  AS altitude_max
        FROM alt;
   ELSIF is_vectorized IS NULL THEN
```

2023-09-15 17:14 UTC, camillemonchicourt commented on src/ref_geo/migrations/versions/1fdac7036dd9_rewrite_fct_get_altitude_intersection.py
> +              IF is_vectorized IS NULL THEN
Oui, intéressant. A priori bien plus performant ?

2024-10-23 07:47 UTC, merged