ref_geo_linear
PnX-SI/RefGeo pull request #4
Opened 2022-09-15 10:03 UTC by joelclems

2022-09-15 15:41 UTC, bouttier requested changes

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    num_version VARCHAR,
C’est quoi ref_name / ref_version / num_version ? Si c’est pour faire comme l_areas, les types correspondent pas (varchar(200), int, varchar(50))

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    id_type INTEGER NOT NULL,
Les linéaires ont déjà un type, pourquoi rajouter un type sur les groupes ?
À mettre un type sur les groupes, il manque sans doute une contraintes pour forcer les linéaires d’un groupe à avoir le même type.

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/models.py
> +    num_version = db.Column(db.Unicode)
types à aligner avec la base

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/models.py
> +    id_type = db.Column(db.Integer, ForeignKey("ref_geo.bib_linears_types.id_type"))
```suggestion
    id_type = db.Column(db.Integer, ForeignKey("ref_geo.bib_linears_types.id_type"), nullable=False)
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/models.py
> +    id_type = db.Column(db.Integer, ForeignKey("ref_geo.bib_linears_types.id_type"))
```suggestion
    id_type = db.Column(db.Integer, ForeignKey("ref_geo.bib_linears_types.id_type"), nullable=False)
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/models.py
> +    linear_name = db.Column(db.Unicode)
```suggestion
    name = db.Column(db.Unicode)
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/models.py
> +    linear_code = db.Column(db.Unicode)
```suggestion
    code = db.Column(db.Unicode)
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    type_code VARCHAR NOT NULL,
```suggestion
    code VARCHAR NOT NULL,
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    type_name VARCHAR NOT NULL,
```suggestion
    name VARCHAR NOT NULL,
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    type_desc VARCHAR,
```suggestion
    desc VARCHAR,
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    linear_name VARCHAR NOT NULL,
```suggestion
    name VARCHAR NOT NULL,
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    enable BOOLEAN,
```suggestion
    enable BOOLEAN NOT NULL DEFAULT TRUE,
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    group_name VARCHAR,
```suggestion
    name VARCHAR,
```

2022-09-15 15:41 UTC, bouttier commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    group_code VARCHAR,
```suggestion
    code VARCHAR,
```

2022-09-16 07:35 UTC, joelclems commented on src/ref_geo/migrations/data/ref_geo_linear.sql
> +    num_version VARCHAR,
C'est calqué sur les l_aeras, effectivement il y a une coquille dans les types

2022-09-16 07:38 UTC, joelclems commented on src/ref_geo/models.py
> +    type_desc = db.Column(db.Unicode)
c'est calqué sur la table `bib_aera_type`, je ne sais pas si nommer les variables avec la redondance est la bonne pratique, et c'est ok pour moi de la changer, mais c'est homogène avec l'existant dans geonature

2022-09-19 09:47 UTC, bouttier commented on src/ref_geo/models.py
> +    type_desc = db.Column(db.Unicode)
Après concertation, on s’est mit d’accord pour arrêter d’ajouter de la redondance aux champs. À noter qu’il n’y avait pas de règle très établie sur quel champs devait être préfixé par le nom de la table et quel champs n’en avait pas besoin …

2022-09-19 12:20 UTC, amandine-sahl commented on src/ref_geo/models.py
> +    type_desc = db.Column(db.Unicode)
Je comprend l'idée, mais en même temps cette table fait echo à bib_area_type ce qui fait qu'il aurait deux tables très proches mais avec des conventions différentes. Est-ce que ce n'est pas un principe à appliquer sur les nouveaux "pans" de la base de données.

2022-09-21 06:12 UTC, camillemonchicourt commented on src/ref_geo/models.py
> +    type_desc = db.Column(db.Unicode)
En effet, vu que ce sont 2 tables à côté, similaires et que l'on va manipuler ensemble, c'est un peu embêtant que celles-ci aient une logique de nommage différente.
Il vaudra peut-être mieux renommer les 2 en même temps pour rester en cohérence ?
Et/ou commencer par simplifier uniquement le nommage des modèles python ?

2022-10-07 13:13 UTC, merged

2022-10-17 16:21 UTC, camillemonchicourt commented
Attention, il y a une table qui est une fois nommée ``t_linear_groups`` et une fois ``l_linear_groups``

2022-10-17 17:13 UTC, bouttier commented
Bien vu, j’étais passé à côté, fixé : 543a0f67303bfce2e8a774ec04a5a61937a14c26